/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/
import React from 'react';

interface PolicyProps {
  onClose: () => void;
}

const TermsOfUse: React.FC<PolicyProps> = ({ onClose }) => {
  return (
    <div className="policy-container">
      <h1>Terms of Use</h1>
      <p><em>Last Updated: July 24, 2024</em></p>

      <h2>Acceptance of Terms</h2>
      <p>
        By accessing and using the TRĒSOR DẼSIGN application ("the Service"), you accept and agree to be bound by the terms and provisions of this agreement.
      </p>

      <h2>Description of Service</h2>
      <p>
        The Service is an exploratory creative tool that uses artificial intelligence to generate text and art based on user-provided topics. The service is provided for informational and entertainment purposes only and should not be considered a factual resource.
      </p>

      <h2>User Responsibilities</h2>
      <p>
        You are solely responsible for the inputs you provide to the Service. You agree not to use the Service to generate content that is unlawful, harmful, defamatory, obscene, or otherwise objectionable. Automated scraping, data mining, or any form of systematic data collection from this service is strictly prohibited.
      </p>

      <h2>Content Disclaimer</h2>
      <p>
        All content is generated by an AI model. TRĒSOR DẼSIGN does not guarantee the accuracy, completeness, or reliability of any information provided by the Service. You acknowledge that you use any content generated by the Service at your own risk.
      </p>
      
      <h2>Intellectual Property</h2>
      <p>
        The Service, including its design, branding, and underlying code, is the property of TRĒSOR DẼSIGN. Your use of the Service does not grant you any ownership rights to the application itself.
      </p>

      <h2>Limitation of Liability</h2>
      <p>
        In no event shall TRĒSOR DẼSIGN be liable for any direct, indirect, incidental, or consequential damages arising out of the use or inability to use the Service.
      </p>

      <h2>Changes to Terms</h2>
      <p>
        We reserve the right to modify these terms at any time. Your continued use of the Service after any such changes constitutes your acceptance of the new terms.
      </p>
      
      <div className="back-button-container">
        <button onClick={onClose} className="back-button">Back to App</button>
      </div>
    </div>
  );
};

export default TermsOfUse;
